package Vista;

import java.awt.Color;
import java.awt.color.ColorSpace;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
       /* this.setExtendedState(MAXIMIZED_BOTH);
        btnNose.setBackground(new Color(22, 160, 133  ));
        btnIngreso.setBackground(new Color(22, 160, 133    ));
        btnSalida.setBackground(new Color(22, 160, 133  ));
        btnEstacionados.setBackground(new Color(22, 160, 133  ));
        jPanel1.setBackground(new Color(19, 141, 117  ));
        jMenuBar1.setBackground(new Color(19, 141, 117  ));
        jLabel2.setForeground(new Color(247, 249, 249));
        jLabel3.setForeground(new Color(247, 249, 249));
        panelOculto1.setVisible(false);
        panelOculto2.setVisible(false);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEstacionados = new javax.swing.JButton();
        btnIngreso = new javax.swing.JButton();
        btnNose = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        btnmenuIngresar = new javax.swing.JMenuItem();
        btnmenuSacar = new javax.swing.JMenuItem();
        btnInformes = new javax.swing.JMenu();
        btnListado = new javax.swing.JMenu();
        btnmenuEstacionados = new javax.swing.JMenuItem();
        btnmenuFacturados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1130, 630));

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1130, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("            Estación de Servicio");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 720, 60));

        btnEstacionados.setBackground(new java.awt.Color(97, 88, 51));
        btnEstacionados.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btnEstacionados.setText("Estacionados");
        btnEstacionados.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnEstacionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstacionadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstacionadosMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEstacionadosMouseReleased(evt);
            }
        });
        btnEstacionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstacionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 490, 90));

        btnIngreso.setBackground(new java.awt.Color(97, 88, 51));
        btnIngreso.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btnIngreso.setText("Entrada");
        btnIngreso.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnIngreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresoMouseExited(evt);
            }
        });
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 490, 80));

        btnNose.setBackground(new java.awt.Color(97, 88, 51));
        btnNose.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btnNose.setText("Facturas");
        btnNose.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnNose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoseMouseExited(evt);
            }
        });
        btnNose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoseActionPerformed(evt);
            }
        });
        jPanel1.add(btnNose, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 490, 80));

        btnSalida.setBackground(new java.awt.Color(97, 88, 51));
        btnSalida.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btnSalida.setText("Salida");
        btnSalida.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnSalida.setBorderPainted(false);
        btnSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalida.setMaximumSize(new java.awt.Dimension(35, 21));
        btnSalida.setMinimumSize(new java.awt.Dimension(35, 21));
        btnSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalidaMouseExited(evt);
            }
        });
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 490, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Mustang.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1200, 630));

        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setForeground(new java.awt.Color(255, 51, 51));

        btnMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu.setForeground(new java.awt.Color(0, 102, 102));
        btnMenu.setText("Vehiculos");
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N

        btnmenuIngresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        btnmenuIngresar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnmenuIngresar.setForeground(new java.awt.Color(0, 102, 102));
        btnmenuIngresar.setText("Ingresar");
        btnmenuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuIngresarActionPerformed(evt);
            }
        });
        btnMenu.add(btnmenuIngresar);

        btnmenuSacar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        btnmenuSacar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnmenuSacar.setForeground(new java.awt.Color(0, 102, 102));
        btnmenuSacar.setText("Sacar");
        btnmenuSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuSacarActionPerformed(evt);
            }
        });
        btnMenu.add(btnmenuSacar);

        jMenuBar1.add(btnMenu);

        btnInformes.setBackground(new java.awt.Color(0, 102, 102));
        btnInformes.setForeground(new java.awt.Color(0, 102, 102));
        btnInformes.setText("Informes");
        btnInformes.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jMenuBar1.add(btnInformes);

        btnListado.setBackground(new java.awt.Color(255, 255, 255));
        btnListado.setForeground(new java.awt.Color(0, 102, 102));
        btnListado.setText("Listado");
        btnListado.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N

        btnmenuEstacionados.setBackground(new java.awt.Color(255, 255, 255));
        btnmenuEstacionados.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnmenuEstacionados.setForeground(new java.awt.Color(0, 102, 102));
        btnmenuEstacionados.setText("Estacionados");
        btnmenuEstacionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuEstacionadosActionPerformed(evt);
            }
        });
        btnListado.add(btnmenuEstacionados);

        btnmenuFacturados.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnmenuFacturados.setForeground(new java.awt.Color(0, 102, 102));
        btnmenuFacturados.setText("Facturados");
        btnmenuFacturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuFacturadosActionPerformed(evt);
            }
        });
        btnListado.add(btnmenuFacturados);

        jMenuBar1.add(btnListado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        frmIngreso objIngreso = new frmIngreso();
        objIngreso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnNoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoseActionPerformed
        // TODO add your handling code here:
        Facturados facturas = null;
        try {
            facturas = new Facturados();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        facturas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNoseActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        frmSalida objSalida = null;
        try {
            objSalida = new frmSalida();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objSalida.setVisible(true);
         this.setVisible(false);
        objSalida.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnmenuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuIngresarActionPerformed
        //System.out.println("Fue presionado");
        frmIngreso objIngreso = new frmIngreso();
        objIngreso.setVisible(true);
        this.setVisible(false);
        objIngreso.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmenuIngresarActionPerformed

    private void btnmenuSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuSacarActionPerformed
        frmSalida objSalida = null;
        try {
            objSalida = new frmSalida();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objSalida.setVisible(true);
        this.setVisible(false);
        objSalida.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmenuSacarActionPerformed

    private void btnmenuEstacionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuEstacionadosActionPerformed
        frmListado objListado = null;
        try {
            objListado = new frmListado();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objListado.setVisible(true);
        this.setVisible(false);
        objListado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmenuEstacionadosActionPerformed

    private void btnEstacionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionadosActionPerformed
        // TODO add your handling code here:
        
        frmListado objListado = null;
        try {
            objListado = new frmListado();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objListado.setVisible(true);
         this.setVisible(false);
        objListado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnEstacionadosActionPerformed

    private void btnNoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoseMouseEntered
        // TODO add your handling code here:
        btnNose.setBackground(new Color(97,88,51  ));
        
    }//GEN-LAST:event_btnNoseMouseEntered

    private void btnNoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoseMouseExited
        // TODO add your handling code here:
        btnNose.setBackground(new Color(97,88,51  ));
        
    }//GEN-LAST:event_btnNoseMouseExited

    private void btnEstacionadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionadosMouseEntered
        // TODO add your handling code here:
       // btnEstacionados.setBackground(new Color(ColorSpace.TYPE_RGB));
       btnEstacionados.setBackground(new Color(97,88,51  ));
    }//GEN-LAST:event_btnEstacionadosMouseEntered

    private void btnEstacionadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionadosMouseExited
        // TODO add your handling code here:
         btnEstacionados.setBackground(new Color(97,88,51  ));
    }//GEN-LAST:event_btnEstacionadosMouseExited

    private void btnIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoMouseEntered
        // TODO add your handling code here:
        btnIngreso.setBackground(new Color(97,88,51  ));
       // entradaCoche.setText("Aquí puedes ingresar la patente de tu auto");
      /*  entradaCoche.setForeground(new  Color(46, 64, 83  ));
        panelOculto1.setVisible(true);
        panelOculto1.setBackground(new  Color(253, 235, 208));
       */
    }//GEN-LAST:event_btnIngresoMouseEntered

    private void btnIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoMouseExited
        // TODO add your handling code here:
        btnIngreso.setBackground(new Color(97,88,51  ));
       // panelOculto1.setVisible(false);
    }//GEN-LAST:event_btnIngresoMouseExited

    private void btnSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseEntered
        // TODO add your handling code here:
        btnSalida.setBackground(new Color(97,88,51  ));
       /* panelOculto2.setVisible(true);
        panelOculto2.setBackground(new  Color(253, 235, 208));
        salidaCoche.setForeground(new  Color(46, 64, 83  ));
        */
    }//GEN-LAST:event_btnSalidaMouseEntered

    private void btnSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseExited
        // TODO add your handling code here:
         btnSalida.setBackground(new Color(97,88,51  ));
       //  panelOculto2.setVisible(false);
    }//GEN-LAST:event_btnSalidaMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(new Color(166, 172, 175));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(new Color(247, 249, 249));
    }//GEN-LAST:event_jLabel2MouseExited

    private void btnEstacionadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstacionadosMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEstacionadosMouseReleased

    private void btnmenuFacturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuFacturadosActionPerformed
        // TODO add your handling code here:
        Facturados objFacturados = null;
        try {
            objFacturados = new Facturados();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objFacturados.setVisible(true);
        this.setVisible(false);
        objFacturados.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_btnmenuFacturadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstacionados;
    private javax.swing.JMenu btnInformes;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JMenu btnListado;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JButton btnNose;
    private javax.swing.JButton btnSalida;
    private javax.swing.JMenuItem btnmenuEstacionados;
    private javax.swing.JMenuItem btnmenuFacturados;
    private javax.swing.JMenuItem btnmenuIngresar;
    private javax.swing.JMenuItem btnmenuSacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
